// moodData.ts
export type Mood = {
  label: string;
  color: string;
  energy: 'High' | 'Low' | '';
  pleasantness: 'High' | 'Low' | '';
};

export const moodData: Mood[] = [
  { label: '격분한1', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진2', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는3', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인4', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'High' },
  { label: '행복한5', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'High' },
  { label: '우울한6', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한7', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는8', color: 'rgb(147,196,125)', energy: 'High', pleasantness: 'High' },
  { label: '평온한9', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는10', color: 'rgb(147,196,125)', energy: 'High', pleasantness: 'High' },
  
  { label: '격분한11', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진12', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는13', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인14', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한15', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },

  { label: '격분한', color: 'rgb(223,32,32)', energy: 'High', pleasantness: 'Low' },
  { label: '공황에 빠진', color: 'rgb(229,84,84)', energy: 'High', pleasantness: 'Low' },
  { label: '스트레스 받는', color: 'rgb(232,108,108)', energy: 'High', pleasantness: 'Low' },
  { label: '긍정적인', color: 'rgb(255,209,87)', energy: 'High', pleasantness: 'High' },
  { label: '행복한', color: 'rgb(255,242,153)', energy: 'High', pleasantness: 'High' },
  { label: '우울한', color: 'rgb(53,80,155)', energy: 'Low', pleasantness: 'Low' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  { label: '평온한', color: 'rgb(147,196,125)', energy: 'Low', pleasantness: 'High' },
  { label: '자신감 있는', color: 'rgb(245,183,87)', energy: 'High', pleasantness: 'High' },
  
  // 총 100개의 항목을 채우기 위한 빈 데이터
  // 100개를 채울 때까지 계속 추가
];
